### ISSUE TITLE
Reconstruction for full length sequences

### ISSUE THREAD

**Issue by matbeale** [simonrharris/pyjar#1]
Hi Simon,

I know the usual use case for this would probably be either single genes or a SNP alignment, but I want to relate the ancestral SNPs back to genome position. However, when I try to run this for a small tree (~22 taxa) using a full length bacterial genome alignment, I get errors.

```Traceback (most recent call last):
  File "/nfs/users/nfs_m/mb29/programs/pyjar/pyjar.py", line 416, in <module>
    main()
  File "/nfs/users/nfs_m/mb29/programs/pyjar/pyjar.py", line 412, in main
    jar(args.alignment, args.tree, args.info, args.prefix, args.verbose)
  File "/nfs/users/nfs_m/mb29/programs/pyjar/pyjar.py", line 342, in jar
    node.r=node.C[i]
KeyError: None``` 

This is your code sniping that refers to "node.r=node.C[i]"

332                 #Traverse the tree from the root in the direction of the OTUs, assigning to each node its most likely ancestral character as follows:
333                 threestart=time.clock()
334                 for node in tree.preorder_node_iter():
335 
336                         try:
337                                 #5a. Visit an unreconstructed internal node x whose father y has already been reconstructed. Denote by i the reconstructed amino acid at node y.
338                                 i=node.parent_node.r
339                         except AttributeError:
340                                 continue
341                         #5b. Reconstruct node x by choosing Cx(i).
342                         node.r=node.C[i]
343                         #new_alignment[node.taxon.label].append(node.r)
344 


If I give pyjar the equivalent multiple sequence alignment preprocessed with sites-sites, it works fine... Can pyjar handle full length sequences?   

Thanks

**Comment by tauqeer9** [comment]
I am also getting a very similar error-

Reading alignment file: coreGeneAlnFinal.fasta
Guessing file is in fasta format
Trying to open file coreGeneAlnFinal.fasta as fasta
Alignment read successfully
Alignment size: 371 taxa and 977782 sites
Reading tree file: coreGenomeRooted.tree
Using default JC rates and frequencies
Frequencies: 0.25, 0.25, 0.25, 0.25
Rates: 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
Finding unique base patterns
Time taken to find unique base patterns: 224.69788200000002 seconds
Unique base patterns: 21924
Reconstructing sites on tree
Traceback (most recent call last):
  File "./pyjar.py", line 428, in <module>
    main()
  File "./pyjar.py", line 424, in main
    jar(args.alignment, args.tree, args.info, args.prefix, args.verbose)
  File "./pyjar.py", line 354, in jar
    node.r=node.C[i]
KeyError: None
